# Generated by Django 5.0.14 on 2025-12-31 08:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contribution Type',
                'verbose_name_plural': 'Contribution Types',
                'db_table': 'contribution_types',
            },
        ),
        migrations.CreateModel(
            name='ContributionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_contributions', models.IntegerField(default=0)),
                ('active_members', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summaries', to='contributions.contributiontype')),
            ],
            options={
                'verbose_name': 'Contribution Summary',
                'verbose_name_plural': 'Contribution Summaries',
                'db_table': 'contribution_summaries',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('mpesa_transaction_code', models.CharField(max_length=20, unique=True)),
                ('mpesa_phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_contributions', to=settings.AUTH_USER_MODEL)),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='contributions.contributiontype')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'db_table': 'contributions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['member', '-submitted_at'], name='contributio_member__3d7f59_idx'), models.Index(fields=['status', '-submitted_at'], name='contributio_status_197c87_idx'), models.Index(fields=['mpesa_transaction_code'], name='contributio_mpesa_t_e04d9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SACCOBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('last_contribution_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contributions.contributiontype')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sacco_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SACCO Balance',
                'verbose_name_plural': 'SACCO Balances',
                'db_table': 'sacco_balances',
                'unique_together': {('member', 'contribution_type')},
            },
        ),
    ]
