# Generated by Django 5.0.14 on 2026-01-02 10:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('ENTRY', 'Entry Application'), ('EXIT', 'Exit Application')], max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=17)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('member_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField(help_text='Reason for entry/exit')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('supporting_document_1', models.FileField(blank=True, null=True, upload_to='applications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('supporting_document_2', models.FileField(blank=True, null=True, upload_to='applications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('STAGE_1', 'Stage 1 - Initial Review'), ('STAGE_2', 'Stage 2 - Verification'), ('STAGE_3', 'Stage 3 - Final Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('current_stage', models.PositiveIntegerField(default=0)),
                ('stage_1_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('stage_1_comments', models.TextField(blank=True, null=True)),
                ('stage_1_status', models.CharField(blank=True, max_length=10, null=True)),
                ('stage_2_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('stage_2_comments', models.TextField(blank=True, null=True)),
                ('stage_2_status', models.CharField(blank=True, max_length=10, null=True)),
                ('stage_3_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('stage_3_comments', models.TextField(blank=True, null=True)),
                ('stage_3_status', models.CharField(blank=True, max_length=10, null=True)),
                ('final_decision', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10, null=True)),
                ('final_comments', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_1_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_1_applications', to=settings.AUTH_USER_MODEL)),
                ('stage_2_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_2_applications', to=settings.AUTH_USER_MODEL)),
                ('stage_3_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_3_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', '-submitted_at'], name='application_user_id_b20d82_idx'), models.Index(fields=['status', '-submitted_at'], name='application_status_04cde2_idx')],
            },
        ),
    ]
